apiVersion: v1
kind: Pod
metadata:
  name: temp-postgres-pod
spec:
  containers:
  - name: postgres-client
    image: postgres:13
    command: ["sleep"]
    args: ["3600"] # Keeps the pod running for 1 hour