apiVersion: v1
kind: Service
metadata:
  name: tenant-proxy
  labels:
    app: tenant-proxy
spec:
  type: {{ .Values.tenantProxy.service.type }}
  ports:
    - port: {{ .Values.tenantProxy.service.port }}
      targetPort: {{ .Values.tenantProxy.service.targetPort }}
      name: http
  selector:
    app: tenant-proxy
