apiVersion: v1
kind: ConfigMap
metadata:
  name: endorser1-agent-config
  labels:
    app: endorser-agent-1
data:
  RUST_LOG: {{ .Values.endorserAgent1.config.RUST_LOG | quote }}
  ACAPY_ENDORSER_1_ADMIN_PORT: {{ .Values.endorserAgent1.config.ACAPY_ENDORSER_1_ADMIN_PORT | quote }}
  ACAPY_ENDORSER_1_HTTP_PORT: {{ .Values.endorserAgent1.config.ACAPY_ENDORSER_1_HTTP_PORT | quote }}
  ACAPY_ENDORSER_1_ENDPOINT: {{ .Values.endorserAgent1.config.ACAPY_ENDORSER_1_ENDPOINT | quote }}
  ENDORSER_AGENT_NAME: {{ .Values.endorserAgent1.config.ENDORSER_AGENT_NAME | quote }}
  ENDORSER_1_ACAPY_READ_ONLY_MODE: {{ .Values.endorserAgent1.config.ENDORSER_1_ACAPY_READ_ONLY_MODE | quote }}
  ENDORSER_1_WEBHOOK_URL: {{ .Values.endorserAgent1.config.ENDORSER_1_WEBHOOK_URL | quote }}
  ACAPY_GENESIS_URL_1: {{ .Values.endorserAgent1.config.ACAPY_GENESIS_URL_1 | quote }}
  ENDORSER_1_ACAPY_WALLET_TYPE: {{ .Values.endorserAgent1.config.ENDORSER_1_ACAPY_WALLET_TYPE | quote }}
  ENDORSER_1_ACAPY_WALLET_STORAGE_TYPE: {{ .Values.endorserAgent1.config.ENDORSER_1_ACAPY_WALLET_STORAGE_TYPE | quote }}
  ENDORSER_1_ACAPY_WALLET_DATABASE: {{ .Values.endorserAgent1.config.ENDORSER_1_ACAPY_WALLET_DATABASE | quote }}
  ENDORSER_1_POSTGRESQL_HOST: {{ .Values.rds.host | quote }}
  POSTGRESQL_PORT: {{ .Values.rds.port | quote }}
  POSTGRESQL_DB: {{ .Values.rds.databases.endorser1 | quote }}
