apiVersion: v1
kind: Secret
metadata:
  name: endorser-agent-secrets
type: Opaque
data:
  ENDORSER_ACAPY_WALLET_ENCRYPTION_KEY: {{ .Values.endorserAgent.secrets.ENDORSER_ACAPY_WALLET_ENCRYPTION_KEY | quote }}
  POSTGRESQL_USER: {{ .Values.rds.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.rds.password | quote }}
  ACAPY_ENDORSER_SEED: {{ .Values.endorserAgent.secrets.ACAPY_ENDORSER_SEED | quote }}
  ENDORSER_ACAPY_ADMIN_URL_API_KEY: {{ .Values.endorserAgent.secrets.ENDORSER_ACAPY_ADMIN_URL_API_KEY | quote }}