apiVersion: v1
kind: ConfigMap
metadata:
  name: endorser-agent-config
  labels:
    app: endorser-agent
data:
  RUST_LOG: {{ .Values.endorserAgent.config.RUST_LOG | quote }}
  ACAPY_ENDORSER_ADMIN_PORT: {{ .Values.endorserAgent.config.ACAPY_ENDORSER_ADMIN_PORT | quote }}
  ACAPY_ENDORSER_HTTP_PORT: {{ .Values.endorserAgent.config.ACAPY_ENDORSER_HTTP_PORT | quote }}
  ACAPY_ENDORSER_ENDPOINT: {{ .Values.endorserAgent.config.ACAPY_ENDORSER_ENDPOINT | quote }}
  ENDORSER_AGENT_NAME: {{ .Values.endorserAgent.config.ENDORSER_AGENT_NAME | quote }}
  ENDORSER_ACAPY_READ_ONLY_MODE: {{ .Values.endorserAgent.config.ENDORSER_ACAPY_READ_ONLY_MODE | quote }}
  ENDORSER_WEBHOOK_URL: {{ .Values.endorserAgent.config.ENDORSER_WEBHOOK_URL | quote }}
  ACAPY_GENESIS_URL: {{ .Values.endorserAgent.config.ACAPY_GENESIS_URL | quote }}
  ENDORSER_ACAPY_WALLET_TYPE: {{ .Values.endorserAgent.config.ENDORSER_ACAPY_WALLET_TYPE | quote }}
  ENDORSER_ACAPY_WALLET_STORAGE_TYPE: {{ .Values.endorserAgent.config.ENDORSER_ACAPY_WALLET_STORAGE_TYPE | quote }}
  ENDORSER_ACAPY_WALLET_DATABASE: {{ .Values.endorserAgent.config.ENDORSER_ACAPY_WALLET_DATABASE | quote }}
  ENDORSER_POSTGRESQL_HOST: {{ .Values.rds.host | quote }}
  POSTGRESQL_PORT: {{ .Values.rds.port | quote }}
  POSTGRESQL_DB: {{ .Values.rds.databases.endorser | quote }}
  
