apiVersion: v1
kind: ConfigMap
metadata:
  name: endorser-api1-config
data:
  POSTGRESQL_HOST: {{ .Values.rds.host | quote }}
  POSTGRESQL_PORT: {{ .Values.rds.port | quote }}
  POSTGRESQL_DB: {{ .Values.rds.databases.endorser1 | quote }}
  ENVIRONMENT: {{ .Values.endorserApi1.config.ENVIRONMENT | quote }}
  TRACTION_WEBHOOK_URL: {{ .Values.endorserApi1.config.TRACTION_WEBHOOK_URL | quote }}
  ENDORSER_API_PORT: {{ .Values.endorserApi1.config.ENDORSER_API_PORT | quote }}
  ACAPY_ADMIN_URL: {{ .Values.endorserApi1.config.ACAPY_ADMIN_URL | quote }}
