apiVersion: v1
kind: Secret
metadata:
  name: endorser-api1-secrets
type: Opaque
data:
  ENDORSER_API_ADMIN_USER: {{ .Values.endorserApi1.secrets.ENDORSER_API_ADMIN_USER | quote }}
  ENDORSER_API_ADMIN_KEY: {{ .Values.endorserApi1.secrets.ENDORSER_API_ADMIN_KEY | quote }}
  ACAPY_ADMIN_URL_API_KEY: {{ .Values.endorserApi1.secrets.ACAPY_ADMIN_URL_API_KEY | quote }}
  ACAPY_WEBHOOK_URL_API_KEY: {{ .Values.endorserApi1.secrets.ACAPY_WEBHOOK_URL_API_KEY | quote }}
