apiVersion: v1
kind: ConfigMap
metadata:
  name: traction-agent-config
  labels:
    app: traction-agent
data: 
  TRACTION_ENV: {{ .Values.tractionAgent.config.TRACTION_ENV | quote }}
  ACAPY_ENDPOINT: {{ .Values.tractionAgent.config.ACAPY_ENDPOINT | quote }}
  TRACTION_ACAPY_HTTP_PORT: {{ .Values.tractionAgent.config.TRACTION_ACAPY_HTTP_PORT | quote }}
  TRACTION_ACAPY_ADMIN_PORT: {{ .Values.tractionAgent.config.TRACTION_ACAPY_ADMIN_PORT | quote }}
  TRACTION_ACAPY_WALLET_NAME: {{ .Values.tractionAgent.config.TRACTION_ACAPY_WALLET_NAME | quote }}
  TRACTION_ACAPY_WALLET_SCHEME: {{ .Values.tractionAgent.config.TRACTION_ACAPY_WALLET_SCHEME | quote }}
  TRACTION_MULTITENANCY_CONFIGURATION_WALLET_TYPE: {{ .Values.tractionAgent.config.TRACTION_MULTITENANCY_CONFIGURATION_WALLET_TYPE | quote }}
  TRACTION_MULTITENANCY_CONFIGURATION_WALLET_NAME: {{ .Values.tractionAgent.config.TRACTION_MULTITENANCY_CONFIGURATION_WALLET_NAME | quote }}
  ACAPY_AUTO_PROVISION: {{ .Values.tractionAgent.config.ACAPY_AUTO_PROVISION | quote }}
  ACAPY_WALLET_TYPE: {{ .Values.tractionAgent.config.ACAPY_WALLET_TYPE | quote }}
  ACAPY_WALLET_STORAGE_TYPE: {{ .Values.tractionAgent.config.ACAPY_WALLET_STORAGE_TYPE | quote }}
  ACAPY_LABEL: {{ .Values.tractionAgent.config.ACAPY_LABEL | quote }}
  ACAPY_GENESIS_TRANSACTIONS_LIST: {{ .Values.tractionAgent.config.ACAPY_GENESIS_TRANSACTIONS_LIST | quote }}
  ACAPY_READ_ONLY_LEDGER: {{ .Values.tractionAgent.config.ACAPY_READ_ONLY_LEDGER | quote }}
  ACAPY_LOG_LEVEL: {{ .Values.tractionAgent.config.ACAPY_LOG_LEVEL | quote }}
  ACAPY_MULTITENANT: {{ .Values.tractionAgent.config.ACAPY_MULTITENANT | quote }}
  ACAPY_MULTITENANT_ADMIN: {{ .Values.tractionAgent.config.ACAPY_MULTITENANT_ADMIN | quote }}
  ACAPY_EMIT_NEW_DIDCOMM_PREFIX: {{ .Values.tractionAgent.config.ACAPY_EMIT_NEW_DIDCOMM_PREFIX | quote }}
  ACAPY_EMIT_NEW_DIDCOMM_MIME_TYPE: {{ .Values.tractionAgent.config.ACAPY_EMIT_NEW_DIDCOMM_MIME_TYPE | quote }}
  ACAPY_ENDORSER_ROLE: {{ .Values.tractionAgent.config.ACAPY_ENDORSER_ROLE | quote }}
  ACAPY_ENDORSER_ALIAS: {{ .Values.tractionAgent.config.ACAPY_ENDORSER_ALIAS | quote }}
  ACAPY_AUTO_REQUEST_ENDORSEMENT: {{ .Values.tractionAgent.config.ACAPY_AUTO_REQUEST_ENDORSEMENT | quote }}
  ACAPY_AUTO_WRITE_TRANSACTIONS: {{ .Values.tractionAgent.config.ACAPY_AUTO_WRITE_TRANSACTIONS | quote }}
  ACAPY_AUTO_PROMOTE_AUTHOR_DID: {{ .Values.tractionAgent.config.ACAPY_AUTO_PROMOTE_AUTHOR_DID | quote }}
  ACAPY_CREATE_REVOCATION_TRANSACTIONS: {{ .Values.tractionAgent.config.ACAPY_CREATE_REVOCATION_TRANSACTIONS | quote }}
  ACAPY_NOTIFY_REVOCATION: {{ .Values.tractionAgent.config.ACAPY_NOTIFY_REVOCATION | quote }}
  ACAPY_MONITOR_REVOCATION_NOTIFICATION: {{ .Values.tractionAgent.config.ACAPY_MONITOR_REVOCATION_NOTIFICATION | quote }}
  ACAPY_PRESERVE_EXCHANGE_RECORDS: {{ .Values.tractionAgent.config.ACAPY_PRESERVE_EXCHANGE_RECORDS | quote }}
  ACAPY_AUTO_STORE_CREDENTIAL: {{ .Values.tractionAgent.config.ACAPY_AUTO_STORE_CREDENTIAL | quote }}
  POSTGRESQL_HOST: {{ .Values.rds.host | quote }}
  POSTGRESQL_PORT: {{ .Values.rds.port | quote }}
  POSTGRESQL_DB: {{ .Values.rds.databases.traction | quote }}
  ACAPY_AUTO_ACCEPT_INVITES: {{ .Values.tractionAgent.config.ACAPY_AUTO_ACCEPT_INVITES | quote }}
  ACAPY_AUTO_ACCEPT_REQUESTS: {{ .Values.tractionAgent.config.ACAPY_AUTO_ACCEPT_REQUESTS | quote }}
  ACAPY_AUTO_RESPOND_MESSAGES: {{ .Values.tractionAgent.config.ACAPY_AUTO_RESPOND_MESSAGES | quote }}
  ACAPY_AUTO_RESPOND_CREDENTIAL_REQUEST: {{ .Values.tractionAgent.config.ACAPY_AUTO_RESPOND_CREDENTIAL_REQUEST | quote }}
  ACAPY_AUTO_RESPOND_PRESENTATION_PROPOSAL: {{ .Values.tractionAgent.config.ACAPY_AUTO_RESPOND_PRESENTATION_PROPOSAL | quote }}
  ACAPY_AUTO_VERIFY_PRESENTATION: {{ .Values.tractionAgent.config.ACAPY_AUTO_VERIFY_PRESENTATION | quote }}
  ACAPY_AUTO_PING_CONNECTION: {{ .Values.tractionAgent.config.ACAPY_AUTO_PING_CONNECTION | quote }}
  ACAPY_MONITOR_PING: {{ .Values.tractionAgent.config.ACAPY_MONITOR_PING | quote }}
  ACAPY_PUBLIC_INVITES: {{ .Values.tractionAgent.config.ACAPY_PUBLIC_INVITES | quote }}
  ACAPY_PLUGIN_CONFIG: {{ .Values.tractionAgent.config.ACAPY_PLUGIN_CONFIG | quote }}
  ACAPY_ADMIN_INSECURE_MODE: {{ .Values.tractionAgent.config.ACAPY_ADMIN_INSECURE_MODE | quote }}
