apiVersion: v1
kind: Secret
metadata:
  name: traction-agent-secrets
type: Opaque
data:
  TRACTION_ACAPY_WALLET_ENCRYPTION_KEY: {{ .Values.tractionAgent.secrets.TRACTION_ACAPY_WALLET_ENCRYPTION_KEY | quote }}
  POSTGRESQL_USER: {{ .Values.rds.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.rds.password | quote }}
  ACAPY_ADMIN_API_KEY: {{ .Values.tractionAgent.secrets.ACAPY_ADMIN_API_KEY | quote }}
  ACAPY_MULTITENANT_JWT_SECRET: {{ .Values.tractionAgent.secrets.ACAPY_MULTITENANT_JWT_SECRET | quote }}
